[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: proxy API calls to your backend (uncomment and set your backend URL)
# [[redirects]]
#   from = "/api/*"
#   to = "https://YOUR-BACKEND-HOSTNAME/api/:splat"
#   status = 200
#   force = true
