services:
  - type: web
    name: nc-working-backend
    env: node
    rootDir: nc-working-backend
    plan: starter
    autoDeploy: true
    region: oregon

    buildCommand: npm ci
    startCommand: npm run start

    healthCheckPath: /api/health

    envVars:
      - key: NODE_VERSION
        value: 20
      # Required at runtime — set real values in Render dashboard or via blueprint sync
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      # Optional: if you want to explicitly allow backend origin in CORS
      - key: BACKEND_ORIGIN
        sync: false

    disks:
      - name: uploads
        mountPath: /opt/render/project/src/nc-working-backend/public/uploads
        sizeGB: 1
